version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - sqlite-data:/app/prisma
    depends_on:
      - sqlite
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
      - COMMAND=start
    command: >
      /bin/sh -c "npx prisma migrate deploy && npm run $${COMMAND}"

  sqlite:
    image: nouchka/sqlite3
    container_name: sqlite

volumes:
  sqlite-data:
